version: '2'
services:
  web:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
      - 3000:3000
#      volumes:
#      - "./web:/app/web"
#      - "./App.ts:/app/App.ts"
#      - "./.env:/app/.env"
#      - "./dist:/app/dist"
#      - "./test:/app/test"
#      - "./static:/app/static"
      depends_on:
        - mongo
        - orientdb
      links:
        - mongo
        - orientdb
      environment:
        SECRET: ${APP_SECRET}
        LOCAL: ${LOCAL}
        MONGO_URI: ${MONGO_URI}
        MONGO_URI_LOCAL: ${MONGO_URI_LOCAL}
        MONGO_USER: ${MONGODB_USER}
        MONGO_PASS: ${MONGODB_PASS}
        MONGO_DATABASE: ${MONGODB_DATABASE}
        PRODUCTION: ${APP_PRODUCTION}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_BUCKET: ${AWS_BUCKET}
        TEST: ${TEST}
        PORT: ${APP_PORT}
        DB_TYPE: ${DB_TYPE}
        ORIENTDB_ROOT_PASSWORD: '${ORIENTDB_ROOT_PASSWORD}'
        ORIENTDB_DATABASE: '${ORIENTDB_DATABASE}'
        ORIENTDB_USER:  '${ORIENTDB_USER}'
        ORIENTDB_PASSWORD:  '${ORIENTDB_PASSWORD}'
        ORIENTDB_PORT:  ${ORIENTDB_PORT}
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - 'data:/data/db'
  orientdb:
    image: orientdb
    ports:
      - "2424:2424"
      - "2480:2480"
    environment:
      ORIENTDB_ROOT_PASSWORD: ${ORIENTDB_ROOT_PASSWORD}
    volumes:
      - data:/opt/orientdb/config
      - data:/opt/orientdb/databases
      - data:/opt/orientdb/backup

  
volumes:
  data:
